### ISSUE TITLE
Could not download Dataset

### ISSUE THREAD

**Issue by bobo199830** [cidis/CK-CNN#1]
Hi,

I have the pleasure of reading your paper recently and thank you for ur excellent work. However, I find there is some error when trying to download you dataset(It seems that the resource is expired. The Link is http://www.cidis.espol.edu.ec/es/content/dataset-deep-learning-based-corn-kernel-classification). I would appreciate it if you could send me a copy of your dataset.

Have a nice day!

**Comment by vision-cidis** [comment]
> Hi,
> 
> I have the pleasure of reading your paper recently and thank you for ur excellent work. However, I find there is some error when trying to download you dataset(It seems that the resource is expired. The Link is http://www.cidis.espol.edu.ec/es/content/dataset-deep-learning-based-corn-kernel-classification). I would appreciate it if you could send me a copy of your dataset.
> 
> Have a nice day!

Everything have been solved, please try again.
